### ISSUE TITLE
/usr/share/tessdata not found

### ISSUE THREAD

**Issue by miasinterestinglife** [pcpeasant/pgsocr#1]
On some systems (Ubuntu 24.04 in my case) the tessdata folder is in  /usr/share/tesseract-ocr/5/
It might make sense to extract this into a variable or something else other than hard-coding it. You might also want to note that in the documentation so people can figure this out on their own.

**Comment by pratham-tharwani** [comment]
Definitely an oversight on my part because the current implementation would be incompatible across platforms. From what I can tell tesserocr should be able to find the tessdata folder on it's own but that didn't seem to work for me. I'll add a CLI option to specify the path directly as well as update the README with details for Tesseract installation.
